export default {
  ADD_NODE: 'DATABROWSER_DATA_ADD_NODE',
  ADD_NODES: 'DATABROWSER_DATA_ADD_NODES',
  UPDATE_NODE: 'DATABROWSER_DATA_UPDATE_NODE',
  DELETE_NODE: 'DATABROWSER_DATA_DELETE_NODE',
  QUERY: 'DATABROWSER_DATA_QUERY',
  SET_ORDER: 'DATABROWSER_DATA_SET_ORDER',
  SET_ITEMCOUNT: 'DATABROWSER_DATA_SETITEMCOUNT',
  SET_FILTER: 'DATABROWSER_DATA_SET_FILTER',
}
