export default {
  SET_DATA: 'DATABROWSER_DATA_SET_DATA',
  SET_NODES: 'DATABROWSER_DATA_SET_NODES',
  SET_LOADED: 'DATABROWSER_DATA_SET_LOADED',
  SET_ORDER: 'DATABROWSER_DATA_SET_ORDER',
  SET_ITEMCOUNT: 'DATABROWSER_DATA_SETITEMCOUNT',
  SET_FILTER: 'DATABROWSER_DATA_SET_FILTER',
}
