export default {
  ADD_NODE: 'DATABROWSER_ADD_NODE',
  ADD_NODES: 'DATABROWSER_ADD_NODES',
  UPDATE_NODE: 'DATABROWSER_UPDATE_NODE',
  DELETE_NODE: 'DATABROWSER_DELETE_NODE',
  QUERY: 'DATABROWSER_QUERY',
  ADD_FILTER: 'DATABROWSER_ADD_FILTER',
  REMOVE_FILTER: 'DATABROWSER_REMOVE_FILTER',
  SET_ORDER: 'DATABROWSER_SET_ORDER',
}
