export default {
  TOGGLE_FILTER: 'DATABROWSER_UI_TOGGLE_FILTER',
  HIDE_NEW_ROW: 'DATABROWSER_UI_HIDE_NEW_ROW',
  TOGGLE_NEW_ROW: 'DATABROWSER_UI_TOGGLE_NEW_ROW',
  SET_NODE_SELECTION: 'DATABROWSER_UI_SET_NODE_SELECTION',
  CLEAR_NODE_SELECTION: 'DATABROWSER_UI_CLEAR_NODE_SELECTION',
  TOGGLE_NODE_SELECTION: 'DATABROWSER_UI_TOGGLE_NODE_SELECTION',
  SET_SCROLL_TOP: 'DATABROWSER_UI_SET_SCROLL_TOP',
  SET_LOADING: 'DATABROWSER_UI_SET_LOADING',
  RESET_UI: 'DATABROWSER_UI_RESET_UI',
  ACTIVATE_NEW_NODE_ROW: 'ACTIVATE_NEW_ROW',
  ACTIVATE_SEARCH_ROW: 'ACTIVATE_SEARCH_ROW',
  ACTIVATE_DELETE_NODE_ROW: 'ACTIVATE_DELETE_ROW',
}
